export const MAINSTAGE = "MAINSTAGE";
export const MAINSTAGE_SUCCESS = "MAINSTAGE_SUCCESS";
export const MAINSTAGE_FAIL = "MAINSTAGE_FAIL";
export const MAINARTIST = "MAINARTIST";
export const MAINARTIST_SUCCESS = "MAINARTIST_SUCCESS";
export const MAINARTIST_FAIL = "MAINARTIST_FAIL";
